const ITEMS=[
['Criação e primeiros tempos','Gênesis',50,1,11],['Era patriarcal','Jó',42],['Patriarcas: Abraão, Isaque, Jacó e José','Gênesis',50,12,50],['Êxodo e aliança','Êxodo',40],['Lei, santidade e culto','Levítico',27],['Peregrinação no deserto','Números',36],['Preparação para a terra prometida','Deuteronômio',34],['Conquista da terra','Josué',24],['Tempo dos juízes','Juízes',21],['Rute e a linhagem de Davi','Rute',4],['Samuel, Saul e Davi','1 Samuel',31],['Reinado de Davi','2 Samuel',24],['Genealogias e Davi','1 Crônicas',29],['Salmos em contexto de Davi e culto','Salmos',150],['Salomão e o templo','1 Reis',22,1,11],['Salomão e o templo','2 Crônicas',36,1,9],['Sabedoria de Israel','Provérbios',31],['Sabedoria de Israel','Eclesiastes',12],['Cânticos e adoração','Cânticos',8],['Reino dividido','1 Reis',22,12,22],['Reino dividido e profetas','2 Reis',25],['Reino dividido de Judá','2 Crônicas',36,10,36],['Profetas no período dos reinos','Obadias',1],['Profetas no período dos reinos','Joel',3],['Profetas no período dos reinos','Jonas',4],['Profetas no período dos reinos','Amós',9],['Profetas no período dos reinos','Oseias',14],['Profetas no período dos reinos','Isaías',66],['Profetas no período dos reinos','Miqueias',7],['Profetas no período dos reinos','Naum',3],['Profetas no período dos reinos','Sofonias',3],['Profetas no período dos reinos','Habacuque',3],['Queda de Jerusalém e exílio','Jeremias',52],['Lamento e esperança','Lamentações',5],['Exílio na Babilônia','Daniel',12],['Exílio na Babilônia','Ezequiel',48],['Retorno do exílio','Esdras',10],['Reconstrução e aliança','Neemias',13],['Providência de Deus','Ester',10],['Profetas da restauração','Ageu',2],['Profetas da restauração','Zacarias',14],['Profetas da restauração','Malaquias',4],['Vida e ministério de Jesus','Lucas',24],['Vida e ministério de Jesus','João',21],['Vida e ministério de Jesus','Mateus',28],['Vida e ministério de Jesus','Marcos',16],['Igreja primitiva','Atos',28],['Cartas missionárias de Paulo','Tiago',5],['Cartas missionárias de Paulo','Gálatas',6],['Cartas missionárias de Paulo','1 Tessalonicenses',5],['Cartas missionárias de Paulo','2 Tessalonicenses',3],['Cartas missionárias de Paulo','1 Coríntios',16],['Cartas missionárias de Paulo','2 Coríntios',13],['Cartas missionárias de Paulo','Romanos',16],['Cartas da prisão','Efésios',6],['Cartas da prisão','Filipenses',4],['Cartas da prisão','Colossenses',4],['Cartas da prisão','Filemom',1],['Cartas pastorais e gerais','1 Timóteo',6],['Cartas pastorais e gerais','Tito',3],['Cartas pastorais e gerais','1 Pedro',5],['Cartas pastorais e gerais','Hebreus',13],['Cartas pastorais e gerais','2 Timóteo',4],['Cartas finais','2 Pedro',3],['Cartas finais','Judas',1],['Cartas finais','1 João',5],['Cartas finais','2 João',1],['Cartas finais','3 João',1],['Revelação final','Apocalipse',22]
];
const ARTHUR=[
{titulo:'Deus criou tudo com amor',versiculo:'Gênesis 1:1',historia:'No começo, Deus fez o céu, a terra, a luz, os animais e tudo que existe. Ele fez cada coisa com carinho e viu que era bom. Deus também fez o Arthur com muito amor.',oracao:'Senhor Deus, obrigado porque o Senhor criou tudo e cuida de mim. Amém.',pergunta:'O que Deus criou que você mais gosta?'},
{titulo:'Noé obedeceu a Deus',versiculo:'Gênesis 6:22',historia:'Deus falou com Noé, e Noé escutou. Ele construiu a arca e cuidou de sua família. Deus guardou Noé, os animais e todos que estavam na arca.',oracao:'Papai do céu, me ajuda a obedecer como Noé. Amém.',pergunta:'Como podemos obedecer a Deus hoje?'},
{titulo:'Abraão confiou em Deus',versiculo:'Gênesis 15:6',historia:'Deus fez uma promessa para Abraão. Mesmo sem ver tudo acontecendo na hora, Abraão confiou. Deus sempre cumpre o que promete.',oracao:'Senhor, me ajuda a confiar no Senhor todos os dias. Amém.',pergunta:'Em que você pode confiar em Deus hoje?'},
{titulo:'José perdoou seus irmãos',versiculo:'Gênesis 50:20',historia:'José passou por momentos difíceis, mas Deus estava com ele. Quando reencontrou seus irmãos, José escolheu perdoar e ajudar sua família.',oracao:'Jesus, me ensina a perdoar e amar minha família. Amém.',pergunta:'Quando alguém erra, como podemos perdoar?'},
{titulo:'Moisés foi cuidado por Deus',versiculo:'Êxodo 2:10',historia:'Quando Moisés era bebê, Deus cuidou dele de um jeito especial. Deus tinha um plano bonito para a vida de Moisés e também tem um plano para o Arthur.',oracao:'Deus, obrigado porque o Senhor cuida de mim. Amém.',pergunta:'Quem Deus usa para cuidar de você?'},
{titulo:'Davi venceu com Deus',versiculo:'1 Samuel 17:45',historia:'Davi era pequeno, mas confiava em Deus. Ele enfrentou Golias porque sabia que Deus era maior que qualquer medo.',oracao:'Senhor, me ajuda a ser corajoso e confiar em Ti. Amém.',pergunta:'Do que você não precisa ter medo porque Deus está com você?'},
{titulo:'Daniel orava sempre',versiculo:'Daniel 6:10',historia:'Daniel amava falar com Deus. Mesmo quando era difícil, ele continuava orando. Deus ouviu Daniel e cuidou dele.',oracao:'Papai do céu, quero falar contigo todos os dias. Amém.',pergunta:'Pelo que podemos orar hoje?'},
{titulo:'Jesus ama as crianças',versiculo:'Marcos 10:14',historia:'As crianças queriam chegar perto de Jesus. Jesus ficou feliz com elas e mostrou que cada criança é muito importante para Deus.',oracao:'Jesus, obrigado porque o Senhor me ama e me recebe. Amém.',pergunta:'Como você sabe que Jesus ama você?'},
{titulo:'Jesus acalmou a tempestade',versiculo:'Marcos 4:39',historia:'Os amigos de Jesus ficaram com medo no barco, mas Jesus mandou o vento e o mar ficarem quietinhos. Tudo obedeceu a Jesus.',oracao:'Jesus, quando eu sentir medo, me lembra que o Senhor está comigo. Amém.',pergunta:'O que você faz quando sente medo?'},
{titulo:'O bom samaritano ajudou',versiculo:'Lucas 10:33',historia:'Um homem estava machucado, e alguém parou para ajudar. Jesus ensinou que amar também é cuidar de quem precisa.',oracao:'Senhor, me ensina a ajudar as pessoas com amor. Amém.',pergunta:'Quem você pode ajudar hoje?'},
{titulo:'Jesus é o bom pastor',versiculo:'João 10:11',historia:'Jesus disse que é como um pastor bom, que cuida das suas ovelhinhas. Ele conhece, protege e ama cada uma delas.',oracao:'Jesus, obrigado porque o Senhor cuida de mim como bom pastor. Amém.',pergunta:'Como Jesus cuida de você?'},
{titulo:'Deus ouve nossas orações',versiculo:'1 João 5:14',historia:'Podemos falar com Deus em qualquer lugar. Ele escuta quando agradecemos, pedimos ajuda e contamos o que sentimos.',oracao:'Deus, obrigado porque o Senhor me ouve. Amém.',pergunta:'O que você quer contar para Deus hoje?'}
];
const STORE_KEY='familiaNaPalavraCompleta.v1';
const $=id=>document.getElementById(id);
const todayISO=()=>new Date().toISOString().slice(0,10);
const dateFromISO=iso=>new Date(iso+'T00:00:00');
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const dayDiff=(a,b)=>Math.floor((dateFromISO(b)-dateFromISO(a))/86400000);
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
function chapters(){const out=[];ITEMS.forEach(([p,b,total,a=1,z=total])=>{for(let c=a;c<=z;c++)out.push({p,b,c});});return out;}
function refLine(list){const parts=[];let i=0;while(i<list.length){const {b,c}=list[i];let j=i;while(j+1<list.length&&list[j+1].b===b&&list[j+1].c===list[j].c+1)j++;parts.push(i===j?`${b} ${c}`:`${b} ${c}–${list[j].c}`);i=j+1;}return parts.join('; ');}
function makePlan(){const ch=chapters(),plan=[];let i=0;for(let day=1;day<=365;day++){const leftCh=ch.length-i,leftDays=366-day;let take=Math.round(leftCh/leftDays);take=Math.max(1,Math.min(5,take));if(leftCh-take<leftDays-1)take=leftCh-(leftDays-1);const part=ch.slice(i,i+take);plan.push({period:part[0].p,reading:refLine(part),chapters:part});i+=take;}return plan;}
const PLAN=makePlan();
const defaultState=()=>({activeProfile:'Marcus',startDate:todayISO(),selectedDay:1,profiles:{Marcus:{done:{}},Ingrid:{done:{}}},arthurDone:{}});
let state=load(), bible=null, bookKeyByName={};
function load(){try{const raw=localStorage.getItem(STORE_KEY);return raw?{...defaultState(),...JSON.parse(raw)}:defaultState();}catch(e){return defaultState();}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state));}
function todayPlanDay(){return clamp(dayDiff(state.startDate,todayISO())+1,1,365);}
function profile(){return state.profiles[state.activeProfile]||state.profiles.Marcus;}
function completedCount(){return Object.values(profile().done).filter(Boolean).length;}
function isDone(day=state.selectedDay){return !!profile().done[day];}
function firstUnread(){for(let i=1;i<=365;i++)if(!profile().done[i])return i;return 365;}
async function loadBible(){try{const res=await fetch('data/biblia-acf.json',{cache:'force-cache'});if(!res.ok)throw new Error('Arquivo ausente');bible=await res.json();bookKeyByName={};Object.entries(bible.books||{}).forEach(([key,info])=>{bookKeyByName[normalize(info.name)]=key;});$('bible-status').textContent='ACF carregada';$('bible-status').classList.add('done');renderBible();}catch(err){bible=null;$('bible-status').textContent='Arquivo ausente';$('bible-status').classList.remove('done');$('bible-message').classList.remove('hidden');$('bible-message').innerHTML='O app já está preparado para mostrar o texto completo. Falta subir o arquivo <strong>data/biblia-acf.json</strong> no repositório.';$('bible-text').innerHTML='';}}
function render(){document.querySelectorAll('.chip').forEach(btn=>btn.classList.toggle('active',btn.dataset.profile===state.activeProfile));const day=clamp(state.selectedDay,1,365);state.selectedDay=day;const data=PLAN[day-1],count=completedCount(),percent=Math.round(count/365*100),done=isDone(day),expected=todayPlanDay();$('active-profile-label').textContent=`Leitura de ${state.activeProfile}`;$('day-number').textContent=day;$('period-text').textContent=data.period;$('reading-text').textContent=data.reading;$('progress-text').textContent=`${percent}%`;$('completed-text').textContent=`${count} de 365 dias`;$('progress-bar').style.width=`${percent}%`;$('status-pill').textContent=done?'Concluído':'Pendente';$('status-pill').classList.toggle('done',done);$('complete-btn').textContent=done?'Desmarcar leitura deste dia':'Marcar leitura de hoje como concluída';$('start-date').value=state.startDate;const atrasado=count+1<expected;$('delay-note').classList.toggle('hidden',!atrasado);if(atrasado)$('delay-note').textContent=`Você está no Dia ${count+1}. Hoje seria o Dia ${expected}. Continue com calma, um dia por vez.`;renderBible();renderArthur();save();}
function renderBible(){if(!bible)return;const wrap=$('bible-text'),msg=$('bible-message'),day=PLAN[state.selectedDay-1];wrap.innerHTML='';let totalVerses=0;day.chapters.forEach(ch=>{const key=bookKeyByName[normalize(ch.b)],verses=bible.chapters?.[`${key}.${ch.c}`];const section=document.createElement('section');section.className='chapter';const h=document.createElement('h3');h.textContent=`${ch.b} ${ch.c}`;section.appendChild(h);if(Array.isArray(verses)){verses.forEach(v=>{totalVerses++;const p=document.createElement('p');p.className='verse';const n=document.createElement('span');n.className='verse-number';n.textContent=String(v.v);const t=document.createElement('span');t.textContent=v.t;p.append(n,t);section.appendChild(p);});}else{const p=document.createElement('p');p.className='note';p.textContent='Capítulo não encontrado no arquivo da Bíblia.';section.appendChild(p);}wrap.appendChild(section);});msg.classList.add('hidden');$('bible-status').textContent=`${totalVerses} versículos`;}
function renderArthur(){const idx=dayDiff('2026-01-01',todayISO())%ARTHUR.length,item=ARTHUR[(idx+ARTHUR.length)%ARTHUR.length],done=!!state.arthurDone[todayISO()];$('arthur-verse').textContent=item.versiculo;$('arthur-story-title').textContent=item.titulo;$('arthur-story').textContent=item.historia;$('arthur-prayer').textContent=item.oracao;$('arthur-question').textContent=item.pergunta;$('arthur-status').textContent=done?'Ouvido hoje':'Hoje';$('arthur-status').classList.toggle('done',done);$('arthur-done').textContent=done?'Desmarcar Arthur hoje':'Arthur ouviu hoje';}
document.querySelectorAll('.chip').forEach(btn=>btn.addEventListener('click',()=>{state.activeProfile=btn.dataset.profile;state.selectedDay=firstUnread();render();}));$('start-date').addEventListener('change',e=>{state.startDate=e.target.value||todayISO();state.selectedDay=todayPlanDay();render();});$('prev-day').addEventListener('click',()=>{state.selectedDay=clamp(state.selectedDay-1,1,365);render();});$('next-day').addEventListener('click',()=>{state.selectedDay=clamp(state.selectedDay+1,1,365);render();});$('today-day').addEventListener('click',()=>{state.selectedDay=todayPlanDay();render();});$('complete-btn').addEventListener('click',()=>{profile().done[state.selectedDay]=!isDone();render();});$('next-unread-btn').addEventListener('click',()=>{state.selectedDay=firstUnread();render();});$('reset-profile').addEventListener('click',()=>{if(confirm(`Reiniciar todo o progresso de ${state.activeProfile}?`)){profile().done={};state.selectedDay=1;render();}});$('arthur-done').addEventListener('click',()=>{const k=todayISO();state.arthurDone[k]=!state.arthurDone[k];render();});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
state.selectedDay=firstUnread();render();loadBible();
